language: ruby
script: bundle exec rake spec
rvm:
  - 1.9.3
  # - rbx-19mode
  # - ruby-head - generates "Cannot find Syck parser for YAML"
env:
  global:
    - secure: "OS3pnXOAVRP0QPDl/Nn/0iBPZbrnn9irFYwEbMJ2fGPsV00u4IYDwoIN5Gzb\nX+cXyiPZB0jdQlbiCMaQEYjYig3fgnDhiLj/MnxkVYtILm+0uPSrX2Zf7jvR\nmxCT5jfTSZoPXQeNi9h8rEqvaqKv4z930xp/Z0QNoZLPWdwY5wk="