language: ruby
script: bundle exec rake spec:$SUITE
rvm:
  - ruby-1.9.3
  - ruby-2.0.0
  - ruby-2.1.0
notifications:
  email:
    recipients:
      - drnicwilliams@gmail.com
    on_success: change
    on_failure: always
env:
  matrix:
    - SUITE=unit
    # - SUITE=integration:aws:basic
    # - SUITE=integration:aws:edge
    # - SUITE=integration:aws:edge_prebuilt
    # - SUITE=integration:aws:edge_prebuilt_ami
  global:
    - secure: "OS3pnXOAVRP0QPDl/Nn/0iBPZbrnn9irFYwEbMJ2fGPsV00u4IYDwoIN5Gzb\nX+cXyiPZB0jdQlbiCMaQEYjYig3fgnDhiLj/MnxkVYtILm+0uPSrX2Zf7jvR\nmxCT5jfTSZoPXQeNi9h8rEqvaqKv4z930xp/Z0QNoZLPWdwY5wk="
matrix:
  allow_failures:
    # - rvm: rbx-19mode
    # - rvm: ruby-2.0.0
    - env: SUITE=integration:aws:basic
        